postgresql: &postgresql
  adapter: postgresql
  username: ubuntu
  password: 123456789
  database: parser
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  <<: *<%= ENV['DB'] || 'postgresql' %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults